### ISSUE TITLE
Use with swarm

### ISSUE THREAD

**Issue by raj457036** [toert/django-gitlab-ci-guide#3]
Do you have any tutorial on using docker swarm + this tutorial setup? 
If not will you please make one or give any suggestions?
Thanks

**Comment by toert** [comment]
Thank you for the question. Making a guide about Docker-swarm is not in my plans.

However, you can integrate the tool for your deploy process by replacing deploying commands from the file
https://github.com/toert/django-gitlab-ci-guide/blob/master/devops/deploy.sh
